theme: 'journal'
site_name: Weberjs
pages:
    - Home: 'index.md'
    - Tutorial: tutorial/tutorial.md
    - Core:
        - 'Stitch': core/stitch.md
        - 'TrialTimeline': core/trial_timeline.md
        - 'Logger': core/logger.md
    - Demos:
        - 'AXCPT task': demos/axcpt.md
        - 'Events bonanza': demos/events.md
